# Commented out for the new yml
name: CI2
env:
  SCREENER_API_KEY: ${{ secrets.SCREENER_API_KEY }}
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies üì¶
      #Using npm ci is generally faster than running npm install
      run: |
<<<<<<< HEAD
        # cd my-app
        npm ci
    - name: Build the app üèó
      run: |
        # cd my-app
        npm run build
    - name: Run component tests üî∏
      run: |
        # cd my-app
        npm run test
    - name: Start the app üì§
      run: |
        # cd my-app
=======
        npm ci
    - name: Build the app üèó
      run: |
        npm run build
    - name: Run component tests üî∏
      run: |
        npm run test
    - name: Start the app üì§
      run: |
>>>>>>> 798ce3685b46da2a48ddcf4385b7bf210693dfd8
        npm start &
        npx wait-on --timeout 60000
    - name: Run visual tests üëÅ
      run: |
<<<<<<< HEAD
        # cd my-app
        npm run test:visual
=======
        npm run test:visual
>>>>>>> 798ce3685b46da2a48ddcf4385b7bf210693dfd8
